---
title: "HWO4"
output: github_document
---

```{r}
library(gapminder)
library(tidyverse)
library(tidyr)
library(reshape2)
```

# Data Reshaping Prompt
## Activity # 2
- Make a tibble with one row per year and columns for life expectancy for two or more countries.
* Use knitr::kable() to make this table look pretty in your rendered homework.
* Take advantage of this new data shape to scatterplot life expectancy for one country against that of another.

```{r}
comparative_sea <- gapminder %>% 
  filter(country %in% c("Indonesia","Malaysia","Singapore", "Philippines")) %>% 
  select(year, country, lifeExp)
maritime_le <- comparative_sea %>%
  spread(key = country, value = lifeExp)
knitr::kable(maritime_le)
```

```{r}
sea_plot1 <- ggplot(comparative_sea, aes(x=year, y=lifeExp, color=country)) + geom_point ()
sea_plot1
```

```{r}
minimum_lifeExp <- gapminder %>% 
  group_by(year,continent) %>% 
  summarize(le_minimum = min(lifeExp))
cont_min <- minimum_lifeExp %>%
  spread(key=continent, value=le_minimum)
knitr::kable(cont_min)
```

```{r}
cont_plot <- ggplot(minimum_lifeExp, aes(year, le_minimum, colour=continent)) + geom_point()
cont_plot
```

